#! /bin/sh

#data=32768 * 8 * 10 b
#start=10000000

#finish=`grep 'flow finish' tmp_tcp |cut -d' ' -f5|cut -d, -f1|tail -1`
#dt=`echo "$finish-$start" |bc`
#goodput=`echo "32768 * 8 * 10 * 1000/ $dt" |bc`
#echo "tcp total time                :  $dt,goodput:$goodput"
#echo "$goodput" > tcp_results

#tail -3 tmp_tcp |grep 'drops'|cut -d' ' -f2 >>tcp_results


echo "the n of params is \$#: $#"
echo "present \$*: $*"
echo "current id of process \$$: $$"
echo "last backgroud proc id \$!: $!"
echo "\$@: $@"
echo "settings \$-: $-"
echo "exit stat, 0 means success \$?: $?"
echo "\${#*}: ${#*}"
echo "\${#@}: ${#@}"
echo "\$_: $_"


